services:
    api:
        image: openpodcast/api
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./dist:/app/dist
            - ./db_schema:/app/db_schema
        environment:
            - MYSQL_HOST=db
            - MYSQL_USER=openpodcast
            - MYSQL_PASSWORD=openpodcast
            - MYSQL_DATABASE=openpodcast
            - MYSQL_PORT=3306
            - MYSQL_AUTH_HOST=db
            - MYSQL_AUTH_USER=openpodcast
            - MYSQL_AUTH_PASSWORD=openpodcast
            - MYSQL_AUTH_DATABASE=openpodcast_auth
            - MYSQL_AUTH_PORT=3306
        ports:
            - '8080:8080'
        links:
            - db
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
            - ./dbinit.sql:/docker-entrypoint-initdb.d/1_init.sql
            - ./db_schema/dev_env/db_auth_init.sql:/docker-entrypoint-initdb.d/3_dev_env_auth.sql
            - ./db_schema/manual_auth.sql:/docker-entrypoint-initdb.d/4_manual_auth.sql
            - ./db_schema/dev_env/db_auth_data.sql:/docker-entrypoint-initdb.d/5_dev_env_auth_data.sql
        ports:
            - '33006:3306'
        environment:
            MYSQL_DATABASE: openpodcast
            MYSQL_USER: openpodcast
            MYSQL_ROOT_PASSWORD: openpodcast
            MYSQL_PASSWORD: openpodcast
        command: --innodb-buffer-pool-size=128M --innodb-buffer-pool-chunk-size=64M --key-buffer-size=5M --event-scheduler=ON

volumes:
    mysqldata:
